// The maplibre worker workaround and the shared style helper live in
// mapSetup.ts — every map component imports from there.
import { maplibregl, styleFor } from '../mapSetup';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { animalAvatarSvg } from '@shared/animalAvatarSvg';
import { circlePolygon, circleRing, featureCollection, pointFeature } from '@mobile/map/geo';
import {
  addCareAction,
  Animal,
  CareStatus,
  fetchAnimals,
  fetchCareActionsInBounds,
  fetchCareStatus,
} from '../api';
import {
  FALLBACK_CENTER,
  getCurrentLocation,
  describeLocationError,
  Coordinates,
} from '../location';
import { resolvedThemeName } from '../theme';
import { useBadgeAwards } from '../badgeAwards';
import { AdBanner } from '../components/AdBanner';
import { HeartBurst, HEART_BURST_MS } from '../components/HeartBurst';
import { InstallBanner } from '../install';

// Same rules as mobile's MapScreen: Turkey bounding box, 100 m circles,
// green fading with weight, animals visible at street scale. The basemap is
// the shared pati style (generated by shared/mapstyle/build.mjs, imported
// from mobile via the @mobile alias) — all three clients render the same
// map. Zoom levels are shared numbers with MapScreen; change one, change
// the other.
const TURKEY_BOUNDS = { minLat: 35.8, maxLat: 42.1, minLng: 25.6, maxLng: 44.8 };
const ACTION_CIRCLE_RADIUS_METERS = 100;
// Animals are drawn only near the user (200 m) and once the map is zoomed
// well in (street/building scale): from afar, dozens of avatars covered the
// map, and the user's business is with the animals on their own street
// anyway.
const ANIMAL_RADIUS_METERS = 200;
const ANIMAL_VISIBLE_MIN_ZOOM = 17;
// The scale the map focuses to after leaving food/water: the 100 m circle
// and the animals inside it should be visible.
const CELEBRATE_ZOOM = 18;
const USER_ZOOM = 16;

// The map's own vocabulary — mirrors mobile's theme/colors.ts mapColors.
const CARED = '#34A853';
// Care-circle freshness: weight 0..1 → fill alpha, same numbers as mobile's
// weightToGreenAlpha / MAX_GREEN_ALPHA (the two maps must look alike).
const MAX_GREEN_ALPHA = 0.5;
const USER_RADIUS_STROKE = 'rgba(33, 32, 30, 0.35)';

// The coverage rings' "breathing": the old Leaflet version animated the SVG
// path's opacity via CSS; MapLibre paints on canvas, so a timer modulates
// the layers' opacity expression instead. Paint transitions (300 ms default)
// smooth the steps. Three phase groups so everything doesn't pulse in
// unison (handoff).
const BREATH_PERIOD_MS = 4500;
const BREATH_TICK_MS = 150;

// Same numbers as mobile MapScreen — the interstitial must feel identical
// on every client. Change one, change the other.
const AI_CHECK_MIN_MS = 2000;
const AI_CHECK_RESULT_MS = 900;
const BREATH_MIN = 0.78;

type ViewType = 'food' | 'water';

const EMPTY_FC: GeoJSON.FeatureCollection = { type: 'FeatureCollection', features: [] };

function breathFactors(now: number): [number, number, number] {
  const factors = [0, 1, 2].map((group) => {
    const phase = (now / BREATH_PERIOD_MS + group / 3) * 2 * Math.PI;
    return BREATH_MIN + ((1 - BREATH_MIN) / 2) * (1 + Math.sin(phase));
  });
  return factors as [number, number, number];
}

const breathe = (prop: 'alpha' | 'strokeAlpha', [f0, f1, f2]: [number, number, number]) =>
  [
    '*',
    ['get', prop],
    ['match', ['%', ['get', 'group'], 3], 0, f0, 1, f1, f2],
  ] as maplibregl.ExpressionSpecification;

export default function MapPage() {
  const navigate = useNavigate();
  const mapEl = useRef<HTMLDivElement>(null);
  const mapRef = useRef<maplibregl.Map | null>(null);
  // Latest GeoJSON per source: setStyle (theme change) wipes sources and
  // layers, so `ensureLayers` re-adds them from these refs on style.load.
  const careDataRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const careStrokesRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const careCentersRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const userRingRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const animalMarkersRef = useRef<maplibregl.Marker[]>([]);
  // Request generations for the racy loaders (see loadCircles).
  const circlesSeqRef = useRef(0);
  const animalsSeqRef = useRef(0);
  const statusSeqRef = useRef(0);
  // The last fetched animal list: consulted for which ones are in range for
  // the heart animation (instead of reading back from the markers).
  const animalsDataRef = useRef<Animal[]>([]);
  const zoomedInRef = useRef(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const { celebrate } = useBadgeAwards();
  const [hearts, setHearts] = useState<{ id: number; x: number; y: number }[]>([]);

  const [viewType, setViewType] = useState<ViewType>('food');
  const [status, setStatus] = useState<CareStatus | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);
  // Placeholder "AI is checking the photo" interstitial — same pattern and
  // constants as mobile MapScreen (always approves; the upload runs behind
  // it; a real model later gains the reject path here).
  const [aiCheck, setAiCheck] = useState<'idle' | 'checking' | 'approved'>('idle');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [zoomHint, setZoomHint] = useState(false);
  const [myLocation, setMyLocation] = useState<Coordinates | null>(null);
  // Flips once the (rAF-deferred) map exists, so the data effects below
  // re-run instead of bailing out against a still-null mapRef.
  const [mapReady, setMapReady] = useState(false);

  const typeLabel = viewType === 'food' ? 'mama' : 'su';

  // Animal markers are DOM elements; they follow the zoom gate imperatively
  // (a ref, not an effect) so `syncAnimalMarkers` can also run right after a
  // fetch replaces the marker list.
  const syncAnimalMarkers = useCallback(() => {
    const map = mapRef.current;
    if (!map) return;
    for (const marker of animalMarkersRef.current) {
      if (zoomedInRef.current) marker.addTo(map);
      else marker.remove();
    }
    // Mobile parity: when animals exist but the zoom gate hides them, say so
    // — otherwise a zoomed-out map just looks empty.
    setZoomHint(animalMarkersRef.current.length > 0 && !zoomedInRef.current);
  }, []);

  // The map is built once; data layers refresh in separate effects.
  // Creation is deferred by one animation frame so React StrictMode's
  // dev-mode mount→unmount→mount never creates and immediately removes a
  // half-initialized map (a create/remove/create in the same tick left the
  // second map's style permanently unparsed with maplibre-gl 6.6.0): the
  // first mount cancels the frame before any map exists, only the second
  // mount builds one.
  useEffect(() => {
    if (!mapEl.current || mapRef.current) return;
    let cleanupMap: (() => void) | null = null;
    const frame = requestAnimationFrame(() => {
      cleanupMap = createMap();
    });
    return () => {
      cancelAnimationFrame(frame);
      cleanupMap?.();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function createMap(): (() => void) | null {
    if (!mapEl.current) return null;
    const map = new maplibregl.Map({
      container: mapEl.current,
      style: styleFor(resolvedThemeName()),
      center: [FALLBACK_CENTER.lng, FALLBACK_CENTER.lat],
      zoom: 15,
      maxBounds: [
        [TURKEY_BOUNDS.minLng, TURKEY_BOUNDS.minLat],
        [TURKEY_BOUNDS.maxLng, TURKEY_BOUNDS.maxLat],
      ],
      // Same ceiling as mobile's MAX_ZOOM; the default (22) overzooms into
      // stretched vector tiles.
      maxZoom: 19,
      attributionControl: { compact: true },
    });
    // No zoom control (handoff): pinch and double-tap are enough.

    // Re-added on every style.load: the initial load and each theme switch.
    const ensureLayers = () => {
      if (map.getSource('care')) return;
      map.addSource('care', { type: 'geojson', data: careDataRef.current });
      map.addLayer({
        id: 'care-fill',
        type: 'fill',
        source: 'care',
        paint: { 'fill-color': CARED, 'fill-opacity': ['get', 'alpha'] },
      });
      // Outlines live in their own LineString source: MapLibre native
      // rejects polygons in line layers, and the two clients share the same
      // data shape (see @mobile/map/geo).
      map.addSource('care-strokes', { type: 'geojson', data: careStrokesRef.current });
      map.addLayer({
        id: 'care-stroke',
        type: 'line',
        source: 'care-strokes',
        paint: { 'line-color': CARED, 'line-opacity': ['get', 'strokeAlpha'], 'line-width': 1.5 },
      });
      map.addSource('care-centers', { type: 'geojson', data: careCentersRef.current });
      // The center dot only at street scale: from afar hundreds of dots
      // would speckle the map for no gain.
      map.addLayer({
        id: 'care-centers-dot',
        type: 'circle',
        source: 'care-centers',
        minzoom: ANIMAL_VISIBLE_MIN_ZOOM,
        paint: { 'circle-color': CARED, 'circle-radius': 5 },
      });
      // The user's 200 m range (where animals draw) as a dashed ring — the
      // handoff's depiction.
      map.addSource('user-ring', { type: 'geojson', data: userRingRef.current });
      map.addLayer({
        id: 'user-ring-stroke',
        type: 'line',
        source: 'user-ring',
        minzoom: ANIMAL_VISIBLE_MIN_ZOOM,
        paint: { 'line-color': USER_RADIUS_STROKE, 'line-width': 1.2, 'line-dasharray': [4, 6] },
      });
    };
    map.on('style.load', ensureLayers);

    // Each tick restarts a paint transition, i.e. a full-map repaint — so
    // breathe only when there is something to breathe and the tab is
    // actually visible; otherwise this loop is a silent battery drain on
    // phones (the PWA's main audience).
    const breathTimer = window.setInterval(() => {
      if (document.hidden) return;
      if (careDataRef.current.features.length === 0) return;
      if (!map.getLayer('care-fill')) return;
      const factors = breathFactors(Date.now());
      map.setPaintProperty('care-fill', 'fill-opacity', breathe('alpha', factors));
      map.setPaintProperty('care-stroke', 'line-opacity', breathe('strokeAlpha', factors));
    }, BREATH_TICK_MS);

    const onZoom = () => {
      const next = map.getZoom() >= ANIMAL_VISIBLE_MIN_ZOOM;
      if (next !== zoomedInRef.current) {
        zoomedInRef.current = next;
        syncAnimalMarkers();
      }
    };
    map.on('zoom', onZoom);

    // The OS can flip light/dark while the map is open; the app theme is CSS
    // (instant), the basemap needs a setStyle. ensureLayers restores our
    // sources afterwards; DOM markers survive a style swap on their own.
    const scheme = matchMedia('(prefers-color-scheme: dark)');
    const onScheme = () => map.setStyle(styleFor(resolvedThemeName()));
    scheme.addEventListener('change', onScheme);

    mapRef.current = map;
    setMapReady(true);

    getCurrentLocation()
      .then((loc) => {
        // The location can arrive after leaving the page; guard against the
        // map having been removed.
        if (mapRef.current !== map) return;
        setMyLocation(loc);
        map.jumpTo({ center: [loc.lng, loc.lat], zoom: USER_ZOOM });
        // The user's location: charcoal dot + white ring (styles in
        // theme.css, .user-dot).
        const dot = document.createElement('div');
        dot.className = 'user-dot';
        new maplibregl.Marker({ element: dot }).setLngLat([loc.lng, loc.lat]).addTo(map);
        userRingRef.current = featureCollection([circleRing(loc, ANIMAL_RADIUS_METERS)]);
        (map.getSource('user-ring') as maplibregl.GeoJSONSource | undefined)?.setData(
          userRingRef.current
        );
      })
      .catch(() => {
        /* Without a location we stay on Kadıköy; asked again when adding a record. */
      });

    return () => {
      window.clearInterval(breathTimer);
      scheme.removeEventListener('change', onScheme);
      for (const marker of animalMarkersRef.current) marker.remove();
      animalMarkersRef.current = [];
      map.remove();
      mapRef.current = null;
    };
  }

  const loadCircles = useCallback(async () => {
    const map = mapRef.current;
    if (!map) return;
    // Fast mama↔su toggles race: without this, whichever response lands
    // LAST paints the map, even if it belongs to the deselected layer.
    const seq = ++circlesSeqRef.current;
    const actions = await fetchCareActionsInBounds(TURKEY_BOUNDS, viewType);
    if (seq !== circlesSeqRef.current) return;
    // Studio language: soft fill + a 1.5px outline in the same tone + a
    // center dot. Freshness lives in the fill — newer records are bolder
    // (same numbers as mobile).
    const alphaOf = (action: (typeof actions)[number]) =>
      Math.min(Math.max(Number(action.weight), 0), 1) * MAX_GREEN_ALPHA;
    careDataRef.current = featureCollection(
      actions.map((action, i) => {
        const [lng, lat] = action.location.coordinates;
        return circlePolygon({ lat, lng }, ACTION_CIRCLE_RADIUS_METERS, {
          alpha: alphaOf(action),
          group: i,
        });
      })
    );
    careStrokesRef.current = featureCollection(
      actions.map((action, i) => {
        const [lng, lat] = action.location.coordinates;
        return circleRing({ lat, lng }, ACTION_CIRCLE_RADIUS_METERS, {
          strokeAlpha: Math.min(alphaOf(action) + 0.25, 0.75),
          group: i,
        });
      })
    );
    careCentersRef.current = featureCollection(
      actions.map((action) => {
        const [lng, lat] = action.location.coordinates;
        return pointFeature({ lat, lng });
      })
    );
    (map.getSource('care') as maplibregl.GeoJSONSource | undefined)?.setData(careDataRef.current);
    (map.getSource('care-strokes') as maplibregl.GeoJSONSource | undefined)?.setData(
      careStrokesRef.current
    );
    (map.getSource('care-centers') as maplibregl.GeoJSONSource | undefined)?.setData(
      careCentersRef.current
    );
  }, [viewType]);

  const loadAnimals = useCallback(
    async (around?: Coordinates) => {
      const map = mapRef.current;
      if (!map) return;
      const center = around ?? myLocation ?? FALLBACK_CENTER;
      const seq = ++animalsSeqRef.current;
      const animals: Animal[] = await fetchAnimals(center.lat, center.lng, ANIMAL_RADIUS_METERS);
      if (seq !== animalsSeqRef.current) return;
      animalsDataRef.current = animals;
      for (const marker of animalMarkersRef.current) marker.remove();
      animalMarkersRef.current = animals.map((animal) => {
        const [lng, lat] = animal.location.coordinates;
        // The animal's pattern avatar is the marker itself — the avatar in a
        // 42px white circle (handoff size).
        const el = document.createElement('div');
        el.className = 'animal-marker';
        el.innerHTML = animalAvatarSvg(animal.species, animal.breed, 30);
        el.addEventListener('click', () => navigate(`/hayvanlar/${animal.id}`));
        return new maplibregl.Marker({ element: el }).setLngLat([lng, lat]);
      });
      syncAnimalMarkers();
    },
    [myLocation, navigate, syncAnimalMarkers]
  );

  useEffect(() => {
    if (!mapReady) return;
    loadCircles().catch((err) => setError(err.message));
  }, [mapReady, loadCircles]);

  useEffect(() => {
    if (!mapReady) return;
    loadAnimals().catch(() => {});
  }, [mapReady, loadAnimals]);

  useEffect(() => {
    const center = myLocation ?? FALLBACK_CENTER;
    const seq = ++statusSeqRef.current;
    fetchCareStatus(center.lat, center.lng, viewType)
      .then((s) => {
        if (seq === statusSeqRef.current) setStatus(s);
      })
      .catch(() => {
        if (seq === statusSeqRef.current) setStatus(null);
      });
  }, [myLocation, viewType]);

  /**
   * Hearts rise from the avatars of the animals within range (100 m) of the
   * dropped food/water. The map zooms to that area first (avatars only draw
   * up close); screen points are computed once movement ends (moveend).
   */
  function celebrateNearbyAnimals(origin: Coordinates) {
    const map = mapRef.current;
    if (!map) return;
    const here = new maplibregl.LngLat(origin.lng, origin.lat);
    const affected = animalsDataRef.current.filter((a) => {
      const [lng, lat] = a.location.coordinates;
      return here.distanceTo(new maplibregl.LngLat(lng, lat)) <= ACTION_CIRCLE_RADIUS_METERS;
    });
    const fire = () => {
      if (affected.length === 0) return;
      setHearts(
        affected.map((a) => {
          const [lng, lat] = a.location.coordinates;
          const pt = map.project([lng, lat]);
          return { id: a.id, x: pt.x, y: pt.y };
        })
      );
      window.setTimeout(() => setHearts([]), HEART_BURST_MS + 200);
    };
    map.once('moveend', fire);
    map.flyTo({ center: here, zoom: CELEBRATE_ZOOM, duration: 400 });
  }

  /** Photo picked → get the location → drop the record at the current spot. */
  async function handlePhotoPicked(file: File) {
    setBusy(true);
    setError(null);
    // The upload runs while the interstitial shows; the minimum wait only
    // pads what's left of it (same trick as the add-animal matching screen).
    setAiCheck('checking');
    const startedAt = Date.now();
    try {
      // Without a location (http origin, no permission), instead of blocking
      // the user we use the map center and state the reason: people drop at
      // the spot they're looking at anyway. The mobile app requires the real
      // location; web is more lenient (see docs/NOTES.md).
      let usedFallback: string | null = null;
      const loc = await getCurrentLocation().catch((err) => {
        usedFallback = describeLocationError(err);
        const center = mapRef.current?.getCenter();
        return center ? { lat: center.lat, lng: center.lng } : FALLBACK_CENTER;
      });
      setMyLocation(loc);
      const created = await addCareAction(loc.lat, loc.lng, viewType, file);
      const elapsed = Date.now() - startedAt;
      if (elapsed < AI_CHECK_MIN_MS) {
        await new Promise((resolve) => setTimeout(resolve, AI_CHECK_MIN_MS - elapsed));
      }
      setAiCheck('approved');
      await new Promise((resolve) => setTimeout(resolve, AI_CHECK_RESULT_MS));
      if (usedFallback) setError(`${usedFallback} Kayıt haritanın ortasına düştü.`);
      // aiCheck resets when the modal next opens, not here: resetting before
      // the close would flash the confirm content behind it.
      setConfirmOpen(false);
      await Promise.all([loadCircles(), loadAnimals(loc)]);
      const s = await fetchCareStatus(loc.lat, loc.lng, viewType).catch(() => null);
      if (s) setStatus(s);
      celebrateNearbyAnimals(loc);
      celebrate(created);
    } catch (err) {
      setAiCheck('idle');
      setError(err instanceof Error ? err.message : 'Eklenemedi');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="page fill">
      <div ref={mapEl} className="map-root" />

      <div className="map-top">
        <div className="segment">
          {(['food', 'water'] as const).map((t) => (
            <button
              key={t}
              className={viewType === t ? 'selected' : ''}
              onClick={() => setViewType(t)}
            >
              {t === 'food' ? 'mama' : 'su'}
            </button>
          ))}
        </div>
        {error && <div className="banner">{error}</div>}
        {zoomHint && <div className="zoom-hint">Hayvanları görmek için yakınlaştır</div>}
        {/* The add-to-home-screen invite: hidden when opened from the home
            screen or after "later" (install.tsx). */}
        <InstallBanner compact />
      </div>

      {/* Bottom-right FAB for registering a new animal (sits above the bottom sheet). */}
      <button
        className="fab"
        aria-label="Yeni hayvan ekle"
        style={{ bottom: 'calc(196px + env(safe-area-inset-bottom))' }}
        onClick={() => navigate('/hayvanlar/yeni')}
      >
        +
      </button>

      {/* Bottom sheet: area status + call to action (handoff 3b). The button
          stays even without a status — dropping a record is always possible. */}
      <div className="map-bottom">
        <div className="map-sheet">
          <div className="sheet-handle" />
          <div className="micro">
            {status
              ? status.needsAttention
                ? `${status.radiusMeters} m çevrede kayıt yok`
                : `${status.radiusMeters} m çevrede ${status.actionCount} kayıt`
              : ' '}
          </div>
          <h2>
            {status && !status.needsAttention
              ? `Bu bölgede ${typeLabel} var`
              : `Buralarda ${typeLabel} yok`}
          </h2>
          <p className="muted" style={{ margin: '2px 0 12px' }}>
            {status && !status.needsAttention
              ? 'Taze kayıt bölgeyi canlı tutar; sen de ekleyebilirsin.'
              : 'İlk kaydı sen bırak, bölge yeşile dönsün.'}
          </p>
          <button
            className="btn full"
            onClick={() => {
              // A leftover 'approved' from the previous run would skip the
              // confirm content (aiCheck resets on open, not on close — see
              // handlePhotoPicked).
              setAiCheck('idle');
              setConfirmOpen(true);
            }}
          >
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
            >
              <path d="M4 12h16a8 8 0 0 1-16 0Z" />
              <path d="M9 9v3M15 8v4" />
            </svg>
            {viewType === 'food' ? 'Mama bırak' : 'Su bırak'}
          </button>
          {/* "Buraya" used to read as "the point on the map"; the record
              actually lands at the device location (or the stated fallback).
              Same persistent hint as mobile. */}
          <div
            className="micro"
            style={{
              marginTop: 8,
              textAlign: 'center',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 6,
            }}
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
            >
              <circle cx="12" cy="12" r="7.4" />
              <circle cx="12" cy="12" r="2.2" />
              <path d="M12 2.4v2.6M12 19v2.6M2.4 12H5M19 12h2.6" />
            </svg>
            Kayıt şu anki konumuna işlenir
          </div>
        </div>
      </div>

      {confirmOpen && (
        <div className="backdrop" onClick={() => !busy && setConfirmOpen(false)}>
          <div className="sheet" onClick={(e) => e.stopPropagation()}>
            {aiCheck !== 'idle' ? (
              /* The photo-check interstitial (placeholder AI — see
                 AI_CHECK_MIN_MS). No cancel: the record is already
                 uploading behind it, bounded by the client's timeout. */
              <div style={{ textAlign: 'center', padding: '8px 0 4px' }}>
                <div
                  className="matching-stage"
                  style={{ width: 88, height: 88, margin: '0 auto 12px', position: 'relative' }}
                >
                  {aiCheck === 'checking' ? (
                    <span className="matching-ring" />
                  ) : (
                    <span style={{ fontSize: 44, color: 'var(--success)' }}>✓</span>
                  )}
                </div>
                <h2 style={{ marginBottom: 4 }}>
                  {aiCheck === 'checking' ? 'Yapay zeka fotoğrafı inceliyor' : 'Uygun görünüyor'}
                </h2>
                <p className="muted">
                  {aiCheck === 'checking'
                    ? `Fotoğraftaki ${typeLabel} kontrol ediliyor…`
                    : 'Kayıt haritaya işleniyor.'}
                </p>
              </div>
            ) : (
              <>
                <h2>Bulunduğun yere {typeLabel} bırak</h2>
                {/* Upload failures must be visible HERE: the page-level
                    banner sits behind the backdrop (review finding). */}
                {error && <div className="error">{error}</div>}
                <p className="muted">
                  {typeLabel === 'mama' ? 'Mamayı' : 'Suyu'} bırak ve fotoğrafını çek, haritada
                  herkes görsün. Kayıt şu anki konumuna düşecek.
                </p>
                <input
                  ref={fileRef}
                  type="file"
                  accept="image/*"
                  capture="environment"
                  hidden
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) handlePhotoPicked(file);
                    e.target.value = '';
                  }}
                />
                <button
                  className="btn full"
                  disabled={busy}
                  onClick={() => fileRef.current?.click()}
                >
                  📷 Fotoğrafını çek
                </button>
                <button
                  className="btn ghost full"
                  disabled={busy}
                  onClick={() => setConfirmOpen(false)}
                >
                  Vazgeç
                </button>
                {/* A food brand on the food map, a water brand on the water map. */}
                <AdBanner
                  slot={viewType === 'food' ? 'food_popup' : 'water_popup'}
                  visible={confirmOpen}
                />
              </>
            )}
          </div>
        </div>
      )}

      {hearts.map((h) => (
        <HeartBurst key={`${h.id}-${h.x}-${h.y}`} x={h.x} y={h.y} />
      ))}
    </div>
  );
}
