// The maplibre worker workaround and the shared style helper live in
// mapSetup.ts — every map component imports from there.
import { maplibregl, styleFor } from '../mapSetup';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { gateAddAnimal } from '../addAnimalGate';
import { animalAvatarSvg } from '@shared/animalAvatarSvg';
import { circleRing, featureCollection, pointFeature } from '@mobile/map/geo';
import { logoSvg } from '@shared/logoSvg';
import { layoutStacks } from '@mobile/map/stacks';
import { viewportBoxes } from '@mobile/map/viewport';
import {
  CARE_GLYPH_PATHS,
  CARE_MARKER_SCALE_SMALL,
  CARE_MARKER_SIZE,
  CARE_MARKER_ZOOM_FULL,
  CARE_MARKER_ZOOM_SMALL,
  careMarkerSvg,
  careMarkerVariants,
  ringStep,
  ringTone,
  type CareType,
} from '@mobile/map/careMarkers';
import {
  PETSHOP_MARKER_HEIGHT,
  PETSHOP_MARKER_WIDTH,
  PETSHOP_MIN_ZOOM,
  PETSHOP_THEMES,
  petshopMarkerKey,
  petshopMarkerSvg,
} from '@mobile/map/petshopMarker';
import {
  addCareAction,
  Animal,
  ApiError,
  CareAction,
  CareStatus,
  checkCarePhoto,
  fetchAnimals,
  fetchCareActionsInBounds,
  fetchCareStatus,
  fetchPetshopsInBounds,
  type Petshop,
  type PhotoCheck,
} from '../api';
import {
  getCurrentLocation,
  describeLocationError,
  describeLocationRefusal,
  hasLocationPermission,
  LOCATION_RETRY_LABEL,
  retryLocationByReload,
  takeLocationRetry,
  Coordinates,
  type LocationRetryIntent,
} from '../location';
import { resolvedThemeName } from '../theme';
import { useBadgeAwards } from '../badgeAwards';
import { AdBanner } from '../components/AdBanner';
import { HeartBurst, HEART_BURST_MS } from '../components/HeartBurst';
import { InstallBanner } from '../install';
import { PetshopSheet } from '../components/PetshopSheet';
import '../styles/map.css';

// Same rules as mobile's MapScreen: worldwide, one map for food
// and water whose records are screen-constant markers in a depleting green
// ring (@mobile/map/careMarkers), animals visible at street scale. The
// basemap is the shared pati style (generated by shared/mapstyle/build.mjs,
// imported from mobile via the @mobile alias) — all three clients render
// the same map. Zoom levels are shared numbers with MapScreen; change one,
// change the other.
// The map is worldwide (owner, 2026-09-09 — it used to be locked to a
// Turkey bounding box through the map's maxBounds): without a location it
// opens on the whole world and the records come from the viewport.
const WORLD_CENTER: [number, number] = [20, 20];
// The generated basemap has no low-zoom relief (shared/mapstyle/build.mjs
// drops `natural_earth`), so below zoom 2 the ground paints empty cream —
// the world view opens at 2.2 and the floor is 2 (same as mobile).
const WORLD_ZOOM = 2.2;
const WORLD_MIN_ZOOM = 2;
const VIEWPORT_REFRESH_MS = 350;
// Below this zoom the map centre is not a place: a drop without a location
// is refused instead of landing in the middle of a continent.
const DROP_FALLBACK_MIN_ZOOM = 14;
const ACTION_CIRCLE_RADIUS_METERS = 100;
// Animals are drawn only near the user (500 m, owner decision 2026-09-08 —
// was 200 m) and from neighbourhood scale on (15 — was 17; overlapping
// avatars fan out now, see @mobile/map/stacks). Same numbers as mobile.
// Keep the zoom an integer: the layer's `step` on zoom evaluates at the
// tile's integer zoom, the avatar gate at the fractional camera zoom.
const ANIMAL_RADIUS_METERS = 500;
const ANIMAL_VISIBLE_MIN_ZOOM = 15;
// The scale the map focuses to after leaving food/water: the 100 m circle
// and the animals inside it should be visible.
const CELEBRATE_ZOOM = 18;
const USER_ZOOM = 16;

// The map's own vocabulary — mirrors mobile's theme/colors.ts mapColors.
const USER_RADIUS_STROKE = 'rgba(33, 32, 30, 0.35)';

// The "AI is checking the photo" interstitial is real since ADR-0005: the
// photo goes up during it and the model says whether it shows the food or
// water the user claims. An approved (or unchecked — the model may be off)
// photo comes back as a token; after "uygun görünüyor" the user explicitly
// confirms, and only that confirm creates the record (owner decision). A
// rejected photo shows the model's reason and offers a retake (mobile
// parity).

const CARE_TYPE_LABEL: Record<CareType, string> = { food: 'mama', water: 'su' };
// The callout's own heading, capitalised — the sheet copy uses the lowercase
// labels above mid-sentence.
const CARE_TYPE_TITLE: Record<CareType, string> = { food: 'Mama', water: 'Su' };

// A tapped marker explains itself instead of the add sheet explaining the
// rings (owner, 2026-09-11 demo note 13). Two records closer than this are
// the same spot — a bowl refilled, not two places — and the popup says how
// many are there. Deliberately a distance on the ground, not on screen: the
// answer then does not change as the user zooms. Mobile uses the same rule.
const SAME_SPOT_METERS = 15;

/** "az önce" / "12 dakika önce" / "2 saat önce" — when the record was left. */
function placedAgo(iso: string): string {
  const minutes = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
  if (minutes < 1) return 'az önce bırakıldı';
  if (minutes < 60) return `${minutes} dakika önce bırakıldı`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} saat önce bırakıldı`;
  return `${Math.floor(hours / 24)} gün önce bırakıldı`;
}

/**
 * "18 dakika kaldı" / "2 sa 10 dk kaldı" / "Süresi doldu". The moment comes
 * from the server (`expires_at`); the comparison is the browser's clock, so
 * a badly skewed machine is a few minutes out — the same tolerance the
 * ring's own fade already has.
 */
function remainingLabel(iso: string): string {
  const minutes = Math.floor((new Date(iso).getTime() - Date.now()) / 60000);
  // A row from a server that does not send expires_at yet: say nothing
  // rather than print "NaN sa NaN dk".
  if (!Number.isFinite(minutes)) return 'Süre bilinmiyor';
  if (minutes <= 0) return 'Süresi doldu';
  if (minutes < 60) return `${minutes} dakika kaldı`;
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  return rest === 0 ? `${hours} saat kaldı` : `${hours} sa ${rest} dk kaldı`;
}

/**
 * How many records sit at the same spot as this one — a bowl refilled, not
 * two places. True positions, which a fan seat has pulled apart on screen.
 */
function sameSpotCount(actions: CareAction[], action: CareAction): number {
  const [lng, lat] = action.location.coordinates;
  const here = new maplibregl.LngLat(lng, lat);
  return actions.filter((a) => {
    const [aLng, aLat] = a.location.coordinates;
    return here.distanceTo(new maplibregl.LngLat(aLng, aLat)) <= SAME_SPOT_METERS;
  }).length;
}

/**
 * The popup's markup. Every value in it is ours (a fixed label, a formatted
 * duration, a count) — no user text reaches setHTML.
 */
function carePopupHtml(action: CareAction, sameSpot: number): string {
  const glyph = CARE_GLYPH_PATHS[action.action_type].map((d) => `<path d="${d}" />`).join('');
  const expired = new Date(action.expires_at).getTime() <= Date.now();
  return [
    '<div class="care-popup-head">',
    `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${glyph}</svg>`,
    `<strong>${CARE_TYPE_TITLE[action.action_type]}</strong>`,
    '</div>',
    `<div class="care-popup-line">${placedAgo(action.created_at)}</div>`,
    `<div class="care-popup-line ${expired ? 'expired' : 'left'}">${remainingLabel(
      action.expires_at
    )}</div>`,
    sameSpot > 1 ? `<div class="care-popup-line stack">Aynı noktada ${sameSpot} kayıt</div>` : '',
  ].join('');
}

// Stacked markers (owner, 2026-09-08, P7 item 9) — same rule as mobile's
// MapScreen: from the avatar zoom on, records and avatars that would
// overlap on screen fan out around their spot automatically (no spokes),
// and the user's dot stays put underneath (@mobile/map/stacks). Below it
// the symbol layer's collision placement thins a pile to its freshest.

const EMPTY_FC: GeoJSON.FeatureCollection = { type: 'FeatureCollection', features: [] };

/**
 * Rasterises every marker variant (mobile ships them as PNGs) into the
 * style's image set at the device pixel ratio. setStyle wipes images, so
 * this runs on every style.load; `hasImage` keeps a re-run cheap. Symbol
 * tiles re-layout on their own once an awaited image lands, so the layer
 * may be added before the images are in.
 */
function registerCareMarkerImages(map: maplibregl.Map) {
  const ratio = Math.min(window.devicePixelRatio || 1, 3);
  const px = Math.round(CARE_MARKER_SIZE * ratio);
  for (const { key, type, tone, step, theme } of careMarkerVariants()) {
    if (map.hasImage(key)) continue;
    const img = new Image(px, px);
    img.onload = () => {
      // The decode can outlive the page: map.remove() drops the style and
      // hasImage() would throw on it (review finding).
      if (!map.style || map.hasImage(key)) return;
      const canvas = document.createElement('canvas');
      canvas.width = px;
      canvas.height = px;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;
      ctx.drawImage(img, 0, 0, px, px);
      map.addImage(key, ctx.getImageData(0, 0, px, px), { pixelRatio: ratio });
    };
    img.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(
      careMarkerSvg(type, step, theme, tone)
    )}`;
  }
}

/**
 * The petshop pin, rasterised like the care markers (mobile ships it as a
 * PNG from the same SVG). Re-run on every style.load for the same reason.
 */
function registerPetshopImages(map: maplibregl.Map) {
  const ratio = Math.min(window.devicePixelRatio || 1, 3);
  const w = Math.round(PETSHOP_MARKER_WIDTH * ratio);
  const h = Math.round(PETSHOP_MARKER_HEIGHT * ratio);
  for (const theme of PETSHOP_THEMES) {
    const key = petshopMarkerKey(theme);
    if (map.hasImage(key)) continue;
    const img = new Image(w, h);
    img.onload = () => {
      if (!map.style || map.hasImage(key)) return;
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;
      ctx.drawImage(img, 0, 0, w, h);
      map.addImage(key, ctx.getImageData(0, 0, w, h), { pixelRatio: ratio });
    };
    img.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(petshopMarkerSvg(theme))}`;
  }
}

export default function MapPage() {
  const navigate = useNavigate();
  const mapEl = useRef<HTMLDivElement>(null);
  const mapRef = useRef<maplibregl.Map | null>(null);
  // Latest GeoJSON per source: setStyle (theme change) wipes sources and
  // layers, so `ensureLayers` re-adds them from these refs on style.load.
  const careMarkersRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const userRingRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  // The petshops in the viewport (zoom ≥ PETSHOP_MIN_ZOOM), as the source's
  // data and as rows for the card a tapped pin opens.
  const petshopsRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const petshopRowsRef = useRef<Petshop[]>([]);
  const petshopsSeqRef = useRef(0);
  // The last fetched records, the spot the dot is drawn at and the dot
  // marker itself: the map is imperative, so the stack layout is
  // re-applied from these refs by paintMarkers() whenever records,
  // animals, the dot or the zoom change.
  const actionsRef = useRef<CareAction[]>([]);
  const myLocationRef = useRef<Coordinates | null>(null);
  // The open care callout, if any; removed on the next tap, on a viewport
  // refresh that drops its record, and on unmount.
  const carePopupRef = useRef<maplibregl.Popup | null>(null);
  const userDotRef = useRef<maplibregl.Marker | null>(null);
  const animalMarkersRef = useRef<maplibregl.Marker[]>([]);
  // Request generations for the racy loaders (see loadMarkers).
  const markersSeqRef = useRef(0);
  const animalsSeqRef = useRef(0);
  const statusSeqRef = useRef(0);
  // The last fetched animal list: consulted for which ones are in range for
  // the heart animation (instead of reading back from the markers).
  const animalsDataRef = useRef<Animal[]>([]);
  const zoomedInRef = useRef(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const { celebrate } = useBadgeAwards();
  const [hearts, setHearts] = useState<{ id: number; x: number; y: number }[]>([]);
  // The tapped petshop's card.
  const [selectedPetshop, setSelectedPetshop] = useState<Petshop | null>(null);

  // Which record the open confirm sheet creates; set by the tile pressed.
  const [dropType, setDropType] = useState<CareType>('food');
  // Per-type status around the user (or the fallback center).
  const [statuses, setStatuses] = useState<Record<CareType, CareStatus> | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [chooserOpen, setChooserOpen] = useState(false);
  // Placeholder "AI is checking the photo" interstitial — same pattern and
  // constants as mobile MapScreen (always approves; the upload runs behind
  // it; a real model later gains the reject path here).
  const [aiCheck, setAiCheck] = useState<'idle' | 'checking' | 'approved' | 'rejected'>('idle');
  // The check's answer: the token the confirm redeems, or the reason a
  // photo was turned down.
  const [photoCheck, setPhotoCheck] = useState<PhotoCheck | null>(null);
  const [rejectReason, setRejectReason] = useState<string | null>(null);
  const [pendingPhoto, setPendingPhoto] = useState<File | null>(null);
  // Invalidates in-flight check timers: dismissing mid-check and reopening
  // must not let the stale timer flip a fresh sheet to a photo-less
  // "approved" (review finding). Bumped on open, cancel, and dismiss.
  const aiCheckRunRef = useRef(0);
  // A second tile tap while the browser is still answering must not stack
  // a second request.
  const dropAskInFlightRef = useRef(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // The warning a location answer put up (the banner, and the drop sheet,
  // both show `error`). A later fix makes exactly that text stale — the
  // sheet must not say "Konum izni verilmedi…" right after a grant — while
  // an error set meanwhile (an upload that failed) stays.
  const locationWarningRef = useRef<string | null>(null);
  // The "Konum iznini tekrar iste" a refusal's warning offers, tied to the
  // warning's text: it shows only while `error` is still that text, so an
  // error set meanwhile never carries another action's reload button.
  const [locationRetry, setLocationRetry] = useState<{
    text: string;
    intent: LocationRetryIntent;
  } | null>(null);
  function warnAboutLocation(text: string, retry: LocationRetryIntent | null = null) {
    locationWarningRef.current = text;
    setError(text);
    setLocationRetry(retry ? { text, intent: retry } : null);
  }
  function clearLocationWarning() {
    const stale = locationWarningRef.current;
    if (stale === null) return;
    locationWarningRef.current = null;
    setError((current) => (current === stale ? null : current));
    setLocationRetry((current) => (current?.text === stale ? null : current));
  }
  const retryOffer = locationRetry && error === locationRetry.text ? locationRetry.intent : null;
  const [zoomHint, setZoomHint] = useState(false);
  const [actionsFailed, setActionsFailed] = useState(false);
  // A failed status lookup is not a missing location: the sheet says which.
  const [statusFailed, setStatusFailed] = useState(false);
  // Minted once per pending photo and revoked on replacement/unmount (the
  // blob-URL-in-render lesson from the add form).
  const pendingPhotoUrl = useMemo(
    () => (pendingPhoto ? URL.createObjectURL(pendingPhoto) : null),
    [pendingPhoto]
  );
  useEffect(
    () => () => {
      if (pendingPhotoUrl) URL.revokeObjectURL(pendingPhotoUrl);
    },
    [pendingPhotoUrl]
  );
  const [myLocation, setMyLocation] = useState<Coordinates | null>(null);
  // Flips once the (rAF-deferred) map exists, so the data effects below
  // re-run instead of bailing out against a still-null mapRef.
  const [mapReady, setMapReady] = useState(false);

  const typeLabel = CARE_TYPE_LABEL[dropType];

  // Animal markers are DOM elements; they follow the zoom gate imperatively
  // (a ref, not an effect) so `syncAnimalMarkers` can also run right after a
  // fetch replaces the marker list.
  const syncAnimalMarkers = useCallback(() => {
    const map = mapRef.current;
    if (!map) return;
    for (const marker of animalMarkersRef.current) {
      if (zoomedInRef.current) marker.addTo(map);
      else marker.remove();
    }
    // Mobile parity: when animals exist but the zoom gate hides them, say so
    // — otherwise a zoomed-out map just looks empty.
    setZoomHint(animalMarkersRef.current.length > 0 && !zoomedInRef.current);
  }, []);

  const positionOf = (action: CareAction): Coordinates => {
    const [lng, lat] = action.location.coordinates;
    return { lat, lng };
  };
  const animalPositionOf = (animal: Animal): Coordinates => {
    const [lng, lat] = animal.location.coordinates;
    return { lat, lng };
  };

  /**
   * Where each record and avatar is drawn at a zoom: from the avatar zoom
   * on, overlapping ones take fan seats around their spot; below it the
   * map is empty (everything sits on its own spot).
   */
  const layoutAt = useCallback((zoom: number) => {
    if (zoom < ANIMAL_VISIBLE_MIN_ZOOM) return [];
    const items = [
      ...actionsRef.current.map((action) => ({ id: `care-${action.id}`, at: positionOf(action) })),
      ...animalsDataRef.current.map((animal) => ({
        id: `animal-${animal.id}`,
        at: animalPositionOf(animal),
      })),
    ];
    const me = myLocationRef.current;
    return layoutStacks(items, zoom, me ? [me] : []);
  }, []);

  /** Where each avatar/record is drawn at a zoom (the hearts read this). */
  const seatsAt = useCallback(
    (zoom: number) => new Map(layoutAt(zoom).map((p) => [p.id, p.drawAt])),
    [layoutAt]
  );

  const paintMarkers = useCallback(() => {
    const map = mapRef.current;
    if (!map) return;
    const actions = actionsRef.current;
    const animals = animalsDataRef.current;
    const draw = new Map<string, { drawAt: Coordinates; spot: Coordinates | null }>();
    for (const placed of layoutAt(map.getZoom())) {
      draw.set(placed.id, { drawAt: placed.drawAt, spot: placed.spot });
    }
    careMarkersRef.current = featureCollection(
      actions.map((action) => {
        const weight = Number(action.weight);
        const at = draw.get(`care-${action.id}`)?.drawAt ?? positionOf(action);
        // `step` as a string: the icon key is built with `concat`, and a
        // string leaves no room for an engine to print a number as "5.0".
        return pointFeature(at, {
          id: action.id,
          type: action.action_type,
          tone: ringTone(weight),
          step: String(ringStep(weight)),
          weight,
        });
      })
    );
    const source = (id: string) => map.getSource(id) as maplibregl.GeoJSONSource | undefined;
    source('care-markers')?.setData(careMarkersRef.current);
    // The avatars are DOM markers in the same order as animalsDataRef.
    animals.forEach((animal, i) => {
      const at = draw.get(`animal-${animal.id}`)?.drawAt ?? animalPositionOf(animal);
      animalMarkersRef.current[i]?.setLngLat([at.lng, at.lat]);
    });
  }, [layoutAt]);

  /**
   * The user's location as a small dot with a breathing halo (owner, P7
   * item 9 — the paw pin of 2026-08-31 retired), centred on the coordinate;
   * one marker, moved on every fix. The stack layout keeps its spot clear
   * and the animal range ring follows it.
   */
  const placeUserDot = useCallback(
    (loc: Coordinates) => {
      const map = mapRef.current;
      if (!map) return;
      if (!userDotRef.current) {
        const dot = document.createElement('div');
        dot.className = 'user-dot';
        dot.innerHTML = '<span class="user-dot-halo"></span><span class="user-dot-core"></span>';
        // setLngLat before addTo: a marker added without a position is
        // painted at the map's origin until its next update.
        userDotRef.current = new maplibregl.Marker({ element: dot, anchor: 'center' })
          .setLngLat([loc.lng, loc.lat])
          .addTo(map);
      } else {
        userDotRef.current.setLngLat([loc.lng, loc.lat]);
      }
      myLocationRef.current = loc;
      userRingRef.current = featureCollection([circleRing(loc, ANIMAL_RADIUS_METERS)]);
      (map.getSource('user-ring') as maplibregl.GeoJSONSource | undefined)?.setData(
        userRingRef.current
      );
      paintMarkers();
    },
    [paintMarkers]
  );

  /** The locate button (owner, P7 item 11): a fresh fix, dot and ring
   * follow, then fly there; animals and statuses refetch through the
   * `myLocation` effects. `retried`: the request a retry reloaded for. */
  async function locateMe(retried = false) {
    const map = mapRef.current;
    if (!map) return;
    try {
      const loc = await getCurrentLocation();
      clearLocationWarning();
      setMyLocation(loc);
      placeUserDot(loc);
      map.flyTo({ center: [loc.lng, loc.lat], zoom: USER_ZOOM, duration: 500 });
    } catch (err) {
      const refusal = describeLocationRefusal(err, '', retried);
      if (refusal) warnAboutLocation(refusal.text, refusal.canRetry ? { action: 'locate' } : null);
      else warnAboutLocation(describeLocationError(err));
      setStatusFailed(await hasLocationPermission());
    }
  }

  /** The chooser's "Yeni hayvan": the form opens only with a location. */
  async function addAnimalFromMap(retried = false) {
    const refused = await gateAddAnimal(navigate, retried);
    if (refused) {
      warnAboutLocation(refused.text, refused.canRetry ? { action: 'add-animal' } : null);
    }
  }

  // The map is built once; data layers refresh in separate effects.
  // Creation is deferred by one animation frame so React StrictMode's
  // dev-mode mount→unmount→mount never creates and immediately removes a
  // half-initialized map (a create/remove/create in the same tick left the
  // second map's style permanently unparsed with maplibre-gl 6.6.0): the
  // first mount cancels the frame before any map exists, only the second
  // mount builds one.
  useEffect(() => {
    if (!mapEl.current || mapRef.current) return;
    let cleanupMap: (() => void) | null = null;
    const frame = requestAnimationFrame(() => {
      cleanupMap = createMap();
    });
    return () => {
      cancelAnimationFrame(frame);
      cleanupMap?.();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function createMap(): (() => void) | null {
    if (!mapEl.current) return null;
    const map = new maplibregl.Map({
      container: mapEl.current,
      style: styleFor(resolvedThemeName()),
      center: WORLD_CENTER,
      zoom: WORLD_ZOOM,
      // Same ceiling as mobile's MAX_ZOOM; the default (22) overzooms into
      // stretched vector tiles.
      minZoom: WORLD_MIN_ZOOM,
      maxZoom: 19,
      // The basemap credit left every map surface (owner, demo note 15): it
      // is the last line of the settings sheet now, so the control that used
      // to sit over the map is off. See @mobile/map/attribution.
      attributionControl: false,
    });
    // No zoom control (handoff): pinch and double-tap are enough.

    // Re-added on every style.load: the initial load and each theme switch.
    const ensureLayers = () => {
      if (map.getSource('care-markers')) return;
      registerCareMarkerImages(map);
      map.addSource('care-markers', { type: 'geojson', data: careMarkersRef.current });
      // One symbol layer, same expressions as mobile: the image key from
      // type + ring step + the current theme, icons shrinking toward
      // country zoom, and collision placement where the fresher record
      // (lower sort key) wins.
      map.addLayer({
        id: 'care-markers-icon',
        type: 'symbol',
        source: 'care-markers',
        layout: {
          'icon-image': [
            'concat',
            'care-',
            ['get', 'type'],
            '-',
            ['get', 'tone'],
            '-',
            ['get', 'step'],
            `-${resolvedThemeName()}`,
          ],
          'icon-size': [
            'interpolate',
            ['linear'],
            ['zoom'],
            CARE_MARKER_ZOOM_SMALL,
            CARE_MARKER_SCALE_SMALL,
            CARE_MARKER_ZOOM_FULL,
            1,
          ],
          // From the avatar zoom on the fan has already separated the stacks,
          // so every marker shows; below it collision placement thins a pile
          // to its freshest record (lower sort key wins).
          'icon-allow-overlap': ['step', ['zoom'], false, ANIMAL_VISIBLE_MIN_ZOOM, true],
          'icon-ignore-placement': ['step', ['zoom'], false, ANIMAL_VISIBLE_MIN_ZOOM, true],
          'symbol-sort-key': ['-', 1, ['get', 'weight']],
        },
      });
      // The user's animal range (where animals draw) as a dashed ring — the
      // handoff's depiction.
      map.addSource('user-ring', { type: 'geojson', data: userRingRef.current });
      map.addLayer({
        id: 'user-ring-stroke',
        type: 'line',
        source: 'user-ring',
        minzoom: ANIMAL_VISIBLE_MIN_ZOOM,
        paint: { 'line-color': USER_RADIUS_STROKE, 'line-width': 1.2, 'line-dasharray': [4, 6] },
      });
      // Petshop pins above the care markers, from city scale on. They take
      // no part in collision placement either way: a shop is always shown
      // (there are few), and never hides a care record behind it. The pin
      // points at the shop with its tip, hence the bottom anchor. Not part
      // of the fan layout: a shop is a fixed place, not a pile to spread.
      registerPetshopImages(map);
      map.addSource('petshops', { type: 'geojson', data: petshopsRef.current });
      map.addLayer({
        id: 'petshops-icon',
        type: 'symbol',
        source: 'petshops',
        minzoom: PETSHOP_MIN_ZOOM,
        layout: {
          'icon-image': petshopMarkerKey(resolvedThemeName()),
          'icon-anchor': 'bottom',
          'icon-allow-overlap': true,
          'icon-ignore-placement': true,
        },
      });
    };
    map.on('style.load', ensureLayers);

    const onZoom = () => {
      const next = map.getZoom() >= ANIMAL_VISIBLE_MIN_ZOOM;
      if (next !== zoomedInRef.current) {
        zoomedInRef.current = next;
        syncAnimalMarkers();
        // The stack layout only exists above the gate: repaint on crossing.
        paintMarkers();
      }
    };
    map.on('zoom', onZoom);

    // The stack layout is a screen-space rule: re-seat after every zoom.
    map.on('zoomend', paintMarkers);
    // Worldwide the records follow the viewport (mobile refetches on the
    // region settle); `moveend` covers pans and zooms alike.
    // A pan is a burst of moveend events; the refetch waits for the map to
    // stand still (mobile debounces its region settles the same way).
    // A failed refresh states itself on the map in Turkish and clears on
    // the next success — it must not stick in the page-wide error banner
    // that the add-record modal also shows (review finding).
    let viewportTimer: number | undefined;
    map.on('moveend', () => {
      window.clearTimeout(viewportTimer);
      viewportTimer = window.setTimeout(() => {
        loadMarkers().catch(() => {
          // loadMarkers raised the pill itself; nothing else to say.
        });
        loadPetshops();
      }, VIEWPORT_REFRESH_MS);
    });

    // A tapped marker explains itself (demo note 13). The listener is a
    // plain map click rather than a layer-scoped one: `ensureLayers` re-adds
    // the layer on every style.load, and a layer-scoped listener registered
    // beside it would pile up one handler per theme switch.
    map.on('click', (e) => {
      // Markers and popups are DOM children of the canvas container, so a
      // click on one bubbles here as well: an avatar tap must not also open
      // a callout, and a click inside the open callout must not close it.
      const target = e.originalEvent.target as HTMLElement | null;
      if (target?.closest?.('.maplibregl-marker, .maplibregl-popup')) return;
      // A shop pin draws above the care markers, so it answers first.
      if (map.getLayer('petshops-icon')) {
        const shopHit = map.queryRenderedFeatures(e.point, { layers: ['petshops-icon'] })[0];
        const shop = petshopRowsRef.current.find((p) => p.id === Number(shopHit?.properties?.id));
        if (shop) {
          carePopupRef.current?.remove();
          setSelectedPetshop(shop);
          return;
        }
      }
      if (!map.getLayer('care-markers-icon')) return;
      const hits = map.queryRenderedFeatures(e.point, { layers: ['care-markers-icon'] });
      // Below the avatar zoom only the freshest record of a pile is
      // rendered (collision placement), so that is the one a click can
      // reach — and the one the popup should describe.
      const id = Number(hits[0]?.properties?.id);
      const action = Number.isInteger(id) ? actionsRef.current.find((a) => a.id === id) : undefined;
      carePopupRef.current?.remove();
      if (!action) return;
      // The popup sits on the marker's DRAWN position (the feature's own
      // coordinates, fan seat included); the "same spot" count compares
      // TRUE positions, which a fan has pulled apart.
      const drawn = hits[0].geometry as GeoJSON.Point;
      const sameSpot = sameSpotCount(actionsRef.current, action);
      const popup = new maplibregl.Popup({
        closeButton: true,
        closeOnClick: false,
        // Clear of the marker: its icon is CARE_MARKER_SIZE (44) centred on
        // the coordinate, so the popup starts just above its top edge.
        offset: 24,
        maxWidth: '230px',
        className: 'care-popup',
        // maplibre focuses the popup's first focusable child on every
        // setDOMContent — and loadMarkers re-renders this callout on every
        // viewport refresh, so the default would yank the keyboard back to
        // the × button behind whatever the user had moved on to. The callout
        // is a card of text; nothing in it needs focus to be read.
        focusAfterOpen: false,
      })
        .setLngLat(drawn.coordinates as [number, number])
        .setHTML(carePopupHtml(action, sameSpot))
        .addTo(map);
      // Which record it describes, so a viewport refresh can tell whether
      // that record is still on the map.
      const el = popup.getElement();
      if (el) el.dataset.careId = String(action.id);
      popup.on('close', () => {
        if (carePopupRef.current === popup) carePopupRef.current = null;
      });
      carePopupRef.current = popup;
    });

    // The OS can flip light/dark while the map is open; the app theme is CSS
    // (instant), the basemap needs a setStyle. ensureLayers restores our
    // sources afterwards; DOM markers survive a style swap on their own.
    const scheme = matchMedia('(prefers-color-scheme: dark)');
    const onScheme = () => map.setStyle(styleFor(resolvedThemeName()));
    scheme.addEventListener('change', onScheme);

    mapRef.current = map;
    setMapReady(true);

    // A "Konum iznini tekrar iste" reloaded the page to get here: the action
    // it was offered for runs again (below), its request now one the browser
    // can prompt for. Taken here, not in an effect: this runs once per real
    // mount (the frame above), and taking removes the intent.
    const retry = takeLocationRetry();

    // The map asks for the location every time it opens (owner decision,
    // 2026-09-07); a page that already holds the permission gets no prompt,
    // only the fix. Mobile asks only on the first open of an app session
    // (C2), because there every re-request on a tab focus counts toward
    // Android's two-denial limit and the OS permission check is exact. Web
    // keeps asking: a later open that only read when the Permissions API
    // said 'granted' would lose the location wherever a browser grants the
    // page but goes on reporting 'prompt' — the likely shape of iOS Safari's
    // default per-site "Ask", the phone this PWA is most used on.
    getCurrentLocation()
      .then((loc) => {
        // The location can arrive after leaving the page; guard against the
        // map having been removed.
        if (mapRef.current !== map) return;
        setMyLocation(loc);
        map.jumpTo({ center: [loc.lng, loc.lat], zoom: USER_ZOOM });
        placeUserDot(loc);
      })
      .catch(async () => {
        // Without a location the map stays on the world view. A granted
        // permission that produced no fix is a failed lookup, a refused
        // one is "we don't know where you are" — the sheet says which
        // (mobile does the same with hasLocationPermission).
        if (mapRef.current !== map) return;
        setStatusFailed(await hasLocationPermission());
      });
    // Beside the map's own request, not instead of it (the map asks on every
    // open): both wait on the page's one decision, so a prompt shows once.
    if (retry?.action === 'drop') openDrop(retry.type, true);
    else if (retry?.action === 'locate') locateMe(true);
    else if (retry?.action === 'add-animal') addAnimalFromMap(true);

    return () => {
      scheme.removeEventListener('change', onScheme);
      carePopupRef.current?.remove();
      carePopupRef.current = null;
      for (const marker of animalMarkersRef.current) marker.remove();
      animalMarkersRef.current = [];
      map.remove();
      mapRef.current = null;
    };
  }

  const loadMarkers = useCallback(async () => {
    const map = mapRef.current;
    if (!map) return;
    // Overlapping loads (a drop right after the first load) race: without
    // this, whichever response lands LAST paints the map.
    const seq = ++markersSeqRef.current;
    // Worldwide the viewport decides which records to show
    // (@mobile/map/viewport turns the engine's corners into the server's
    // box — mobile uses the same helper).
    const b = map.getBounds();
    // An antimeridian viewport is two boxes; the records are the union.
    const boxes = viewportBoxes([b.getEast(), b.getNorth()], [b.getWest(), b.getSouth()]);
    let parts: CareAction[][];
    try {
      parts = await Promise.all(boxes.map((box) => fetchCareActionsInBounds(box)));
    } catch (err) {
      // The flag belongs behind the same sequence guard as the data: a
      // stale request must neither raise nor clear it (review finding).
      if (seq === markersSeqRef.current) setActionsFailed(true);
      throw err;
    }
    if (seq !== markersSeqRef.current) return;
    setActionsFailed(false);
    const byId = new Map<number, CareAction>();
    for (const part of parts) for (const action of part) byId.set(action.id, action);
    const actions = [...byId.values()];
    actionsRef.current = actions;
    paintMarkers();
    // The callout ages with the data, the way mobile's does (its content is
    // a memo over the same list): a refresh re-renders it, so the remaining
    // time and the "Aynı noktada N kayıt" count move instead of standing
    // still at whatever they said when the marker was clicked. A refresh
    // that dropped the record it describes closes it, rather than leaving a
    // card about something no longer on the map.
    const openPopup = carePopupRef.current;
    if (openPopup) {
      const open = byId.get(Number(openPopup.getElement()?.dataset.careId));
      if (!open) openPopup.remove();
      else openPopup.setHTML(carePopupHtml(open, sameSpotCount(actions, open)));
    }
  }, [paintMarkers]);

  /**
   * The petshops in the viewport, from city scale on (PETSHOP_MIN_ZOOM;
   * below it the layer draws nothing, so nothing is asked for). A failed
   * fetch keeps the pins already drawn: a shop that was there a pan ago is
   * still there, and the care pill is about records, not shops.
   */
  const loadPetshops = useCallback(async () => {
    const map = mapRef.current;
    if (!map) return;
    const seq = ++petshopsSeqRef.current;
    let shops: Petshop[] = [];
    if (map.getZoom() >= PETSHOP_MIN_ZOOM) {
      const b = map.getBounds();
      const boxes = viewportBoxes([b.getEast(), b.getNorth()], [b.getWest(), b.getSouth()]);
      try {
        const parts = await Promise.all(boxes.map((box) => fetchPetshopsInBounds(box)));
        const byId = new Map<number, Petshop>();
        for (const part of parts) for (const shop of part) byId.set(shop.id, shop);
        shops = [...byId.values()];
      } catch {
        return;
      }
    }
    if (seq !== petshopsSeqRef.current) return;
    petshopRowsRef.current = shops;
    petshopsRef.current = featureCollection(
      shops.map((shop) => {
        const [lng, lat] = shop.location.coordinates;
        return pointFeature({ lat, lng }, { id: shop.id });
      })
    );
    (map.getSource('petshops') as maplibregl.GeoJSONSource | undefined)?.setData(
      petshopsRef.current
    );
  }, []);

  /** Both statuses around a point; a failed pair leaves the sheet cautious. */
  const loadStatuses = useCallback(async (center: Coordinates) => {
    const seq = ++statusSeqRef.current;
    try {
      const [food, water] = await Promise.all([
        fetchCareStatus(center.lat, center.lng, 'food'),
        fetchCareStatus(center.lat, center.lng, 'water'),
      ]);
      if (seq === statusSeqRef.current) {
        setStatuses({ food, water });
        setStatusFailed(false);
      }
    } catch {
      if (seq === statusSeqRef.current) {
        setStatuses(null);
        setStatusFailed(true);
      }
    }
  }, []);

  const loadAnimals = useCallback(
    async (around?: Coordinates) => {
      const map = mapRef.current;
      if (!map) return;
      // Animals are the ones around the user; without a fix there are none
      // to show (the map may be on the whole world).
      const center = around ?? myLocation;
      if (!center) {
        animalsDataRef.current = [];
        for (const marker of animalMarkersRef.current) marker.remove();
        animalMarkersRef.current = [];
        syncAnimalMarkers();
        return;
      }
      const seq = ++animalsSeqRef.current;
      const animals: Animal[] = await fetchAnimals(center.lat, center.lng, ANIMAL_RADIUS_METERS);
      if (seq !== animalsSeqRef.current) return;
      animalsDataRef.current = animals;
      for (const marker of animalMarkersRef.current) marker.remove();
      animalMarkersRef.current = animals.map((animal) => {
        const [lng, lat] = animal.location.coordinates;
        // The animal's pattern avatar is the marker itself — the avatar in a
        // 42px white circle (handoff size).
        const el = document.createElement('div');
        el.className = 'animal-marker';
        // The face cut-out when the animal has one, the pattern avatar
        // otherwise (P3) — the same rule as AnimalAvatar.
        if (animal.cover_thumb_url) {
          const img = document.createElement('img');
          img.src = animal.cover_thumb_url;
          img.alt = '';
          img.width = 30;
          img.height = 30;
          img.style.cssText =
            'width:30px;height:30px;border-radius:50%;object-fit:cover;display:block';
          el.replaceChildren(img);
        } else {
          el.innerHTML = animalAvatarSvg(animal.species, animal.breed, 30);
        }
        el.addEventListener('click', () => navigate(`/hayvanlar/${animal.id}`));
        return new maplibregl.Marker({ element: el }).setLngLat([lng, lat]);
      });
      syncAnimalMarkers();
      // Seat the new markers: the layout moves the markers that exist now,
      // not the ones just removed (review finding).
      paintMarkers();
    },
    [myLocation, navigate, paintMarkers, syncAnimalMarkers]
  );

  useEffect(() => {
    if (!mapReady) return;
    loadMarkers().catch(() => {
      // loadMarkers raised the pill itself.
    });
  }, [mapReady, loadMarkers]);

  useEffect(() => {
    if (!mapReady) return;
    loadAnimals().catch(() => {});
  }, [mapReady, loadAnimals]);

  useEffect(() => {
    if (mapReady) loadPetshops();
  }, [mapReady, loadPetshops]);

  useEffect(() => {
    // Without a fix there is no "here" to judge — the sheet says so
    // instead of describing the fallback centre (review finding).
    // The failure flag is set where the location attempt actually fails
    // (below and in locateMe); this effect only asks for the status of a
    // known place — a fix still in flight must not read as a failure.
    if (myLocation) loadStatuses(myLocation);
    else setStatuses(null);
  }, [myLocation, loadStatuses]);

  /**
   * Hearts rise from the avatars of the animals within range (100 m) of the
   * dropped food/water. The map zooms to that area first (avatars only draw
   * up close); screen points are computed once movement ends (moveend).
   */
  function celebrateNearbyAnimals(origin: Coordinates) {
    const map = mapRef.current;
    if (!map) return;
    const here = new maplibregl.LngLat(origin.lng, origin.lat);
    const affected = animalsDataRef.current.filter((a) => {
      const [lng, lat] = a.location.coordinates;
      return here.distanceTo(new maplibregl.LngLat(lng, lat)) <= ACTION_CIRCLE_RADIUS_METERS;
    });
    const fire = () => {
      if (affected.length === 0) return;
      // Hearts rise from where the avatar is drawn — its fan seat when it
      // shares the spot with the fresh record (review finding).
      const seats = seatsAt(map.getZoom());
      setHearts(
        affected.map((a) => {
          const at = seats.get(`animal-${a.id}`) ?? animalPositionOf(a);
          const pt = map.project([at.lng, at.lat]);
          return { id: a.id, x: pt.x, y: pt.y };
        })
      );
      window.setTimeout(() => setHearts([]), HEART_BURST_MS + 200);
    };
    map.once('moveend', fire);
    map.flyTo({ center: here, zoom: CELEBRATE_ZOOM, duration: 400 });
  }

  /**
   * Photo picked → it goes up and the model looks at it → the approved step
   * waits for an explicit confirm (owner decision — the check must not
   * auto-add); a rejected photo shows the reason and a retake.
   */
  async function handlePhotoPicked(file: File) {
    setError(null);
    setPendingPhoto(file);
    setPhotoCheck(null);
    setRejectReason(null);
    setAiCheck('checking');
    const run = ++aiCheckRunRef.current;
    try {
      const result = await checkCarePhoto(dropType, file);
      if (run !== aiCheckRunRef.current) return;
      setPhotoCheck(result);
      setAiCheck('approved');
    } catch (err) {
      if (run !== aiCheckRunRef.current) return;
      if (err instanceof ApiError && err.code === 'photoRejected') {
        setRejectReason(err.message);
        setAiCheck('rejected');
        return;
      }
      setAiCheck('idle');
      setPendingPhoto(null);
      setError(err instanceof Error ? err.message : 'Fotoğraf yüklenemedi');
    }
  }

  /** The explicit "add it" after the AI check approved the photo. */
  async function handleConfirmDrop() {
    if (!pendingPhoto || !photoCheck) return;
    setBusy(true);
    setError(null);
    // Hoisted: the "already recorded" branch below refreshes around it.
    let loc: Awaited<ReturnType<typeof getCurrentLocation>> | null = null;
    try {
      // Without a location (http origin, no permission), instead of blocking
      // the user we use the map center and state the reason: people drop at
      // the spot they're looking at anyway. The mobile app requires the real
      // location; web is more lenient (see docs/NOTES.md).
      let usedFallback: string | null = null;
      loc = await getCurrentLocation().catch((err) => {
        // The map centre stands in for a fix only while the map is zoomed
        // into a street (worldwide, one pixel can be hundreds of km — a
        // record at the centre of a world view would be nonsense).
        const map = mapRef.current;
        const center = map && map.getZoom() >= DROP_FALLBACK_MIN_ZOOM ? map.getCenter() : null;
        if (!center) {
          const warning = `${describeLocationError(
            err
          )} Kaydı bırakmak için haritayı sokak seviyesine yakınlaştır.`;
          // Shown by the catch below; a later fix clears it like any
          // location warning.
          locationWarningRef.current = warning;
          throw new Error(warning);
        }
        usedFallback = describeLocationError(err);
        return { lat: center.lat, lng: center.lng };
      });
      setMyLocation(loc);
      // The dot, its ring and the layout anchor follow the drop's fix.
      placeUserDot(loc);
      const created = await addCareAction(loc.lat, loc.lng, dropType, photoCheck.photoToken);
      if (usedFallback) setError(`${usedFallback} Kayıt haritanın ortasına düştü.`);
      // aiCheck/pendingPhoto reset when the modal next opens, not here:
      // resetting before the close would flash the confirm content behind it.
      setConfirmOpen(false);
      // The record is already created: a failed refresh states itself on
      // the map (the pill) and must not turn the drop into an error or
      // swallow the badge celebration (review finding).
      await Promise.all([
        loadMarkers().catch(() => {}),
        loadAnimals(loc).catch(() => {}),
        loadStatuses(loc),
      ]);
      celebrateNearbyAnimals(loc);
      celebrate(created);
    } catch (err) {
      // Stay on the approval step so the user can retry the confirm —
      // unless the token has expired, which only a fresh check can fix.
      if (err instanceof ApiError && err.code === 'photoAlreadyUsed') {
        // The earlier confirm went through and its response was lost: the
        // drop exists, so close and refresh like a success — and say so if
        // the same flaky connection fails the refresh too.
        setConfirmOpen(false);
        const at = loc;
        try {
          await Promise.all([
            loadMarkers(),
            at ? loadAnimals(at) : Promise.resolve(),
            at ? loadStatuses(at) : Promise.resolve(),
          ]);
        } catch (refreshErr) {
          setError(refreshErr instanceof Error ? refreshErr.message : 'Harita yenilenemedi');
        }
        return;
      }
      if (err instanceof ApiError && err.code === 'photoTokenInvalid') {
        aiCheckRunRef.current++;
        setAiCheck('idle');
        setPendingPhoto(null);
        setPhotoCheck(null);
      }
      setError(err instanceof Error ? err.message : 'Eklenemedi');
    } finally {
      setBusy(false);
    }
  }

  /** A tile pressed: open the sheet for that type and ask for the location beside it. */
  function openDrop(type: CareType, retried = false) {
    // A leftover 'approved' from the previous run would skip the confirm
    // content (state resets on open, not on close — see handleConfirmDrop).
    aiCheckRunRef.current++;
    setAiCheck('idle');
    setPendingPhoto(null);
    setDropType(type);
    setConfirmOpen(true);
    askForDropLocation(type, retried);
  }

  /**
   * The tile is an action, so it asks the browser (C2, mobile parity): the
   * prompt comes with the sheet, and the guidance answers only a refusal of
   * this request — it used to come from `permissions.query` with no request
   * at all. Two deliberate differences from mobile: the sheet opens at once
   * rather than after the answer (the browser's only request is a whole fix,
   * which can take seconds after a grant; mobile's is the bare permission),
   * and it stays open after a refusal, because web can still drop at the map
   * centre (see docs/NOTES.md). A refusal offers to ask again by reload
   * (location.ts); `retried` marks the request that reload came back for.
   */
  async function askForDropLocation(type: CareType, retried: boolean) {
    if (dropAskInFlightRef.current) return;
    dropAskInFlightRef.current = true;
    try {
      const loc = await getCurrentLocation();
      clearLocationWarning();
      setMyLocation(loc);
      placeUserDot(loc);
    } catch (err) {
      const refusal = describeLocationRefusal(
        err,
        'Konum olmadan bırakmak için haritayı sokak seviyesine yakınlaştır; kayıt haritanın ' +
          'ortasına düşer.',
        retried
      );
      if (refusal) {
        warnAboutLocation(refusal.text, refusal.canRetry ? { action: 'drop', type } : null);
      }
    } finally {
      dropAskInFlightRef.current = false;
    }
  }

  // The status line reads both types at once; unknown counts as missing
  // (the sheet never claims coverage it hasn't seen) — mobile parity.
  const hasFood = !!statuses && !statuses.food.needsAttention;
  const hasWater = !!statuses && !statuses.water.needsAttention;
  // Without a fix there is no "here" to judge (the map may be showing the
  // whole world): say so instead of claiming the area is empty.
  const sheetTitle = !statuses
    ? statusFailed
      ? 'Buranın durumu alınamadı'
      : 'Buranın durumu bilinmiyor'
    : hasFood && hasWater
    ? 'Bu bölgede mama ve su var'
    : hasFood
    ? 'Bu bölgede mama var, su yok'
    : hasWater
    ? 'Bu bölgede su var, mama yok'
    : 'Buralarda mama ve su yok';

  return (
    <div className="page fill">
      <div ref={mapEl} className="map-root" />

      <div className="map-top">
        {error && (
          <div className="banner">
            {error}
            {retryOffer && (
              <button
                className="btn small secondary banner-action"
                onClick={() => retryLocationByReload(retryOffer)}
              >
                {LOCATION_RETRY_LABEL}
              </button>
            )}
          </div>
        )}
        {actionsFailed && <div className="zoom-hint">Kayıtlar yüklenemedi</div>}
        {zoomHint && <div className="zoom-hint">Hayvanları görmek için yakınlaştır</div>}
        {/* The add-to-home-screen invite: hidden when opened from the home
            screen or after "later" (install.tsx). */}
        <InstallBanner compact />
      </div>

      {/* The locate button (P7 item 11) above the sheet. */}
      <button
        className="map-locate"
        aria-label="Konumuma git"
        style={{ bottom: 'calc(178px + env(safe-area-inset-bottom))' }}
        onClick={() => locateMe()}
      >
        <svg
          width="22"
          height="22"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.8"
          strokeLinecap="round"
        >
          <circle cx="12" cy="12" r="7.4" />
          <circle cx="12" cy="12" r="2.2" />
          <path d="M12 2.4v2.6M12 19v2.6M2.4 12H5M19 12h2.6" />
        </svg>
      </button>

      {/* Bottom sheet: both types' status and one "Ekle" that opens the
          chooser (owner, P7 item 10) — mobile parity. */}
      <div className="map-bottom">
        <div className="map-sheet">
          <div className="sheet-handle" />
          <h2>{sheetTitle}</h2>
          <p className="muted" style={{ margin: '2px 0 12px' }}>
            {/* The ring no longer explains itself here (owner, demo note
                13): a tapped marker says what it is and how long it has. */}
            {statuses
              ? 'Kayıt şu anki konumuna düşer.'
              : statusFailed
              ? 'Konum ya da bağlantı hazır olunca burayı gösteririz; kayıt yine şu anki konumuna düşer.'
              : 'Konumunu açınca buranın durumunu gösteririz; kayıt yine şu anki konumuna düşer.'}
          </p>
          {/* The pati logo on the button (owner, P8 item 1): white on the
              gradient, heart cut out. logoSvg is our own static markup. */}
          <button className="btn full" onClick={() => setChooserOpen(true)}>
            <span
              className="btn-logo"
              dangerouslySetInnerHTML={{ __html: logoSvg(20, 'currentColor', 'transparent') }}
            />
            Ekle
          </button>
        </div>
      </div>

      {chooserOpen && (
        <div className="backdrop" onClick={() => setChooserOpen(false)}>
          <div className="sheet" onClick={(e) => e.stopPropagation()}>
            <h2>Ne ekliyorsun?</h2>
            {(
              [
                { key: 'food', label: 'Mama bıraktım' },
                { key: 'water', label: 'Su bıraktım' },
                { key: 'animal', label: 'Yeni hayvan' },
              ] as const
            ).map((choice) => (
              <button
                key={choice.key}
                className="chooser-row"
                onClick={async () => {
                  setChooserOpen(false);
                  if (choice.key === 'animal') {
                    await addAnimalFromMap();
                  } else {
                    openDrop(choice.key);
                  }
                }}
              >
                <span className="chooser-icon">
                  {choice.key === 'animal' ? (
                    <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor">
                      <circle cx="6.4" cy="10.6" r="2.1" />
                      <circle cx="9.9" cy="7.2" r="2.2" />
                      <circle cx="14.1" cy="7.2" r="2.2" />
                      <circle cx="17.6" cy="10.6" r="2.1" />
                      <path d="M12 12.2c2.6 0 5 2.1 5 4.5 0 1.8-1.4 2.9-3 2.9-.9 0-1.4-.4-2-.4s-1.1.4-2 .4c-1.6 0-3-1.1-3-2.9 0-2.4 2.4-4.5 5-4.5Z" />
                    </svg>
                  ) : (
                    <svg
                      width="22"
                      height="22"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.8"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      {CARE_GLYPH_PATHS[choice.key].map((d) => (
                        <path key={d} d={d} />
                      ))}
                    </svg>
                  )}
                </span>
                <span className="chooser-label">{choice.label}</span>
                <span className="chooser-chevron">›</span>
              </button>
            ))}
            <button className="btn ghost full" onClick={() => setChooserOpen(false)}>
              Vazgeç
            </button>
          </div>
        </div>
      )}

      {confirmOpen && (
        <div
          className="backdrop"
          onClick={() => {
            if (busy) return;
            aiCheckRunRef.current++;
            setConfirmOpen(false);
          }}
        >
          <div className="sheet" onClick={(e) => e.stopPropagation()}>
            {/* One file input for every step of the sheet. It used to live
                in the idle branch only, so on the rejected step "Yeniden
                çek" clicked a ref to an unmounted input and did nothing
                (production report, 2026-09-08). */}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              capture="environment"
              hidden
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) handlePhotoPicked(file);
                e.target.value = '';
              }}
            />
            {aiCheck !== 'idle' ? (
              /* The photo-check interstitial (ADR-0005). The photo is up,
                 nothing is recorded; the approved step waits for an
                 explicit confirm, the rejected step offers a retake. */
              <div style={{ textAlign: 'center', padding: '8px 0 4px' }}>
                <div
                  className="matching-stage"
                  style={{ width: 88, height: 88, margin: '0 auto 12px', position: 'relative' }}
                >
                  {aiCheck === 'checking' ? (
                    <span className="matching-ring" />
                  ) : aiCheck === 'rejected' ? (
                    <span style={{ fontSize: 44, color: 'var(--danger)' }}>✕</span>
                  ) : (
                    <span style={{ fontSize: 44, color: 'var(--success)' }}>✓</span>
                  )}
                </div>
                <h2 style={{ marginBottom: 4 }}>
                  {aiCheck === 'checking'
                    ? 'Yapay zeka fotoğrafı inceliyor'
                    : aiCheck === 'rejected'
                    ? 'Bu fotoğraf uygun görünmüyor'
                    : photoCheck?.verdict === 'approved'
                    ? 'Uygun görünüyor'
                    : 'Fotoğraf hazır'}
                </h2>
                <p className="muted">
                  {aiCheck === 'checking'
                    ? `Fotoğraftaki ${typeLabel} kontrol ediliyor…`
                    : aiCheck === 'rejected'
                    ? rejectReason ?? `Fotoğrafta ${typeLabel} görünmüyor. Tekrar çeker misin?`
                    : `${
                        photoCheck?.reason ? `${photoCheck.reason} ` : ''
                      }Kayıt eklensin mi? Şu anki konumuna ${typeLabel} kaydı düşecek.`}
                </p>
                {aiCheck === 'rejected' && (
                  <>
                    {pendingPhotoUrl && (
                      <img
                        src={pendingPhotoUrl}
                        alt=""
                        width={84}
                        height={84}
                        style={{ objectFit: 'cover', borderRadius: 14, margin: '4px auto 12px' }}
                      />
                    )}
                    <button className="btn full" onClick={() => fileRef.current?.click()}>
                      Yeniden çek
                    </button>
                    <button
                      className="btn ghost full"
                      onClick={() => {
                        aiCheckRunRef.current++;
                        setAiCheck('idle');
                        setPendingPhoto(null);
                        setError(null);
                      }}
                    >
                      Vazgeç
                    </button>
                  </>
                )}
                {aiCheck === 'approved' && (
                  <>
                    {error && <div className="error">{error}</div>}
                    {pendingPhotoUrl && (
                      <img
                        src={pendingPhotoUrl}
                        alt=""
                        width={84}
                        height={84}
                        style={{ objectFit: 'cover', borderRadius: 14, margin: '4px auto 12px' }}
                      />
                    )}
                    <button className="btn full" disabled={busy} onClick={handleConfirmDrop}>
                      {busy ? 'Ekleniyor…' : 'Onayla ve ekle'}
                    </button>
                    <button
                      className="btn ghost full"
                      disabled={busy}
                      onClick={() => {
                        aiCheckRunRef.current++;
                        setAiCheck('idle');
                        setPendingPhoto(null);
                        setError(null);
                      }}
                    >
                      Vazgeç
                    </button>
                  </>
                )}
              </div>
            ) : (
              <>
                <h2>Bulunduğun yere {typeLabel} bırak</h2>
                {/* Upload failures must be visible HERE: the page-level
                    banner sits behind the backdrop (review finding). */}
                {error && <div className="error">{error}</div>}
                {/* The sheet's own refusal only: another action's warning
                    must not reload into a different action from here. */}
                {retryOffer?.action === 'drop' && retryOffer.type === dropType && (
                  <button
                    className="btn secondary full"
                    style={{ marginBottom: 12 }}
                    onClick={() => retryLocationByReload(retryOffer)}
                  >
                    {LOCATION_RETRY_LABEL}
                  </button>
                )}
                <p className="muted">
                  {typeLabel === 'mama' ? 'Mamayı' : 'Suyu'} bırak ve fotoğrafını çek, haritada
                  herkes görsün. Kayıt şu anki konumuna düşecek.
                </p>
                <button
                  className="btn full"
                  disabled={busy}
                  onClick={() => fileRef.current?.click()}
                >
                  📷 Fotoğrafını çek
                </button>
                <button
                  className="btn ghost full"
                  disabled={busy}
                  onClick={() => setConfirmOpen(false)}
                >
                  Vazgeç
                </button>
                {/* A food brand under the food sheet, a water brand under the water one. */}
                <AdBanner
                  slot={dropType === 'food' ? 'food_popup' : 'water_popup'}
                  visible={confirmOpen}
                />
              </>
            )}
          </div>
        </div>
      )}

      {selectedPetshop && (
        <PetshopSheet shop={selectedPetshop} onClose={() => setSelectedPetshop(null)} />
      )}

      {hearts.map((h) => (
        <HeartBurst key={`${h.id}-${h.x}-${h.y}`} x={h.x} y={h.y} />
      ))}
    </div>
  );
}
